default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: has_many_throgh_app

test:
  <<: *default
  database: has_many_throgh_app_test

production:
  <<: *default
  database: has_many_throgh_app_pro
